:token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmUiOiIyMDE3LTEwLTA0VDE4OjUzOjQ3LjE5MFoiLCJsb2dpbiI6IiJ9.dWASrT2e4zQV3-QDDJ9hY7u9kjmbCcU8zghRpwQXXVw
:server = http://localhost:8080

### Load KPI

GET :server/kpi/06d48c24-23ee-4b03-95d1-d39322ad16d9
X-Access-Token: :token

### Load KPI 2

GET :server/kpi/1216b892-dfd3-451b-b89b-dbaf6b17d9d6
X-Access-Token: :token

### Load KPI Value

GET :server/kpi/value/1cb04ee95-1ed7-460f-a2d5-613cc58d1bf
X-Access-Token: :token

### Insert KPI

POST :server/kpi/
Content-Type: application/json
X-Access-Token: :token

{
  "name": "KPIName1",
  "consolidationType": "mean",
  "frequency": "day",
  "multipleConsolidationType": "sum",
  "target_type": "kpi",
  "target": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6",
  "target_min_type": "constant",
  "target_min": "5",
  "target_max_type": "percentage",
  "target_max": "1.2"
}

### Insert Data Value
POST :server/kpi/value
Content-Type: application/json
X-Access-Token: :token

{
  "date": "2017-10-15 12:47:50",
  "value": "5.0",
  "weight": "1.0",
  "kpi": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6"
}

### Login

# Login
POST :server/login
login: admin
password: password


