:token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmUiOiIyMDE3LTEwLTA0VDE4OjUzOjQ3LjE5MFoiLCJsb2dpbiI6IiJ9.dWASrT2e4zQV3-QDDJ9hY7u9kjmbCcU8zghRpwQXXVw
:server = http://localhost:8080

### Load KPI

GET :server/kpi/06d48c24-23ee-4b03-95d1-d39322ad16d8
X-Access-Token: :token

### Load KPI 2

GET :server/kpi/06d48c24-23ee-4b03-95d1-d39322ad16d8
X-Access-Token: :token

### Login

# Login
POST :server/login
login: admin
password: password


