:token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmUiOjE1MTU5NjAzODg5NDcsImxvZ2luIjoiIn0.hWKOyZxbBN-hq87dEctow3a2yeF3oEzACTFmhk_ephA
:server = http://localhost:8080

### Load KPI

GET :server/kpi/06d48c24-23ee-4b03-95d1-d39322ad16d9
X-Access-Token: :token

### Load KPI 2

GET :server/kpi/1216b892-dfd3-451b-b89b-dbaf6b17d9d6
X-Access-Token: :token

### Generate Report for KPI 2

POST :server/report/period
Content-Type: application/json
X-Access-Token: :token

{
   "kpi": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6",
   "start": "2017-10-15 00:00:00.000 +00:00",
   "end": "2017-10-28 00:00:00.000 +00:00",
   "frequency": 3
}

### Bulk insert values

POST :server/kpi/values/
Content-Type: application/json
X-Access-Token: :token

{
    "kpi": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6",
    "values" : [{
        "date": "2018-01-01 00:00:00.000 +00:00",
        "value": 52
    }, {
        "date": "2018-01-02 00:00:00.000 +00:00",
        "value": 52
    }]
}

### Load KPI 3

GET :server/kpi/name/KPIName1
X-Access-Token: :token

### Load KPI Value

GET :server/kpi/value/1cb04ee95-1ed7-460f-a2d5-613cc58d1bf
X-Access-Token: :token

### Insert KPI

POST :server/kpi/
Content-Type: application/json
X-Access-Token: :token

{
  "name": "KPI10",
  "consolidationType": "mean",
  "frequency": "day",
  "multipleConsolidationType": "sum",
  "target_type": "kpi",
  "target": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6",
  "target_min_type": "constant",
  "target_min": "5",
  "target_max_type": "percentage",
  "target_max": "1.2"
}

### Insert Data Value
POST :server/kpi/value
Content-Type: application/json
X-Access-Token: :token

{
  "date": "2017-10-15 12:47:50",
  "value": "5.0",
  "weight": "1.0",
  "kpi": "1216b892-dfd3-451b-b89b-dbaf6b17d9d6"
}

### Load KPI by name
GET :server/kpi/name/KPI10
Content-Type: application/json
X-Access-Token: :token


### Delete KPI10
DELETE :server/kpi/8b6d5968-d017-43f0-9d42-223b0e590a30
Content-Type: application/json
X-Access-Token: :token

### Login

# Login
POST :server/login
login: admin
password: password


